/* 
**  mod_teapot.c -- Apache sample teapot module
**  [Autogenerated via ``apxs -n teapot -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_teapot.c
**
**  Then activate it in Apache's apache2.conf file for instance
**  for the URL /teapot in as follows:
**
**    #   apache2.conf
**    LoadModule teapot_module modules/mod_teapot.so
**    <Location /teapot>
**    SetHandler teapot
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /teapot and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/teapot 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_teapot.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"

static int teapot_handler(request_rec *r)
{
    r->content_type = "text/html";      
    apr_table_set(r->notes, "error-notes", "<p>I'm a teapot.");
    apr_table_set(r->notes, "verbose-error-to", "*");
    r->status_line = "418 I'm a teapot";

    return 418;
}

static void teapot_register_hooks(apr_pool_t *p)
{
    ap_hook_handler(teapot_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA teapot_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    teapot_register_hooks  /* register hooks                      */
};
